export const LAUNCH_YEARS = 'LAUNCH_YEARS';
export const LOADING_INDICATOR = 'LOADING_INDICATOR';
export const SUCCESSFUL_LAND = 'SUCCESSFUL_LAND';
export const SUCCESSFUL_LAUNCH = 'SUCCESSFUL_LAUNCH';
export const CARD_DETAILS = 'CARD_DETAILS';
export const NO_RECORDS = 'NO_RECORDS';
